name: ila
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  calculator: 
    path: 'packages/calculator'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
